pool:
  vmImage: 'ubuntu-latest'

variables:
- name: cypressVersion
  value: '12.17.2'  # Update this with the desired Cypress version if needed

steps:
- script: |
    npm install -g cypress@${{ variables.cypressVersion }}
  displayName: 'Install Cypress'

- script: |
    npm install
  displayName: 'Install dependencies'

- script: |
    npm run runOnChrome
  displayName: 'Run Cypress tests (Chrome)'

- task: PublishTestResults@2
  